# Dockerfile.consumer

# Use the official Python image.
FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the RabbitMQ consumer service code
COPY rabbit.py .

# Run the RabbitMQ consumer script
CMD ["python", "rabbit.py"]