# Dockerfile.api

# Use the official Python image.
FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the FastAPI app code
COPY controller.py .


# Expose the FastAPI default port

# Run the FastAPI app
CMD ["uvicorn", "controller:app", "--host", "0.0.0.0", "--port", "8000"]